server:
  port: 9999
spring:
  application:
    name: suixingpay-config
  profiles:
    active: sit

---
spring:
  profiles: dev
  cloud:
    config:
      server:
        native:
          search-locations: file:///Users/admin/work/IdeaProjects/grouptactic/group-tac/grouptactic-repository/
---
spring:
  profiles: sit
  cloud:
    config:
      server:
        git:
#          username: ""
#          password: ""
          timeout: 60000
          uri: https://github.com/99129/suixingpay-microservice.git
          search-paths: repository
          default-label: ${label:develop}


