zuul:
  ignoredServices: "*"
  host:
    socket-timeout-millis: 60000
    connect-timeout-millis: 60000
  routes:
    test-server-1:
      stripPrefix: true
      path: /test-server-1/**
      url: test-server-1
    test-user-server:
      sensitiveHeaders:
      stripPrefix: true
      path: /test-user-server/**
      url: test-user-server