#ribbon配置
ribbon:
  maxAutoRetries: 1
  ReadTimeout: 60000
  ConnectTimeout: 6000
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 60000
      fallback:
        isolation:
          semaphore:
            maxConcurrentRequests: 200
  threadpool:
    default:
      coreSize: 203
      maxQueueSize: 202
      queueSizeRejectionThreshold: 201
#路由表
zuul:
  ignoredServices: "*"
  host:
    socket-timeout-millis: 60000
    connect-timeout-millis: 60000
  routes:
    suixingpay-department:
      stripPrefix: true
      path: /suixingpay-department/**
      url: suixingpay-department
    suixingpay-employee:
      sensitiveHeaders:
      stripPrefix: true
      path: /suixingpay-employee/**
      url: suixingpay-employee