#负载均衡配置
ribbon:
  maxAutoRetries: 1
  ReadTimeout: 60000
  ConnectTimeout: 6000
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 60000
      fallback:
        isolation:
          semaphore:
            maxConcurrentRequests: 200
  threadpool:
    default:
      coreSize: 200
      maxQueueSize: 200
      queueSizeRejectionThreshold: 200